# Generated by Django 4.1.4 on 2022-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_0', models.CharField(max_length=200)),
                ('field_1', models.IntegerField(default=10)),
                ('field_2', models.FloatField(null=True)),
                ('field_3', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
